// Generated by scripts/extract-titan-art.py; original artwork pixels are preserved.
import type { ImageSourcePropType } from 'react-native';
import type { CardFace } from '../domain/cards';
import { isDreamwalker } from '../domain/titan-selection';

const images: Record<string, ImageSourcePropType> = {
  "Mazerunner": require("../../assets/titan-art/mazerunner.jpg"),
  "Dreamwalker": require("../../assets/titan-art/dreamwalker.jpg"),
  "Logicbreaker": require("../../assets/titan-art/logicbreaker.jpg"),
  "Gamechanger": require("../../assets/titan-art/gamechanger.jpg"),
  "Earthshaker": require("../../assets/titan-art/earthshaker.jpg"),
  "Skyseer": require("../../assets/titan-art/skyseer.jpg"),
  "Dawnburner": require("../../assets/titan-art/dawnburner.jpg"),
  "Truthbearer": require("../../assets/titan-art/truthbearer.jpg"),
  "Immortal Truthbearer": require("../../assets/titan-art/immortal-truthbearer.jpg"),
  "Returner": require("../../assets/titan-art/returner.jpg"),
  "Firestarter": require("../../assets/titan-art/firestarter.jpg"),
  "Abysswatcher": require("../../assets/titan-art/abysswatcher.jpg"),
  "Ascender": require("../../assets/titan-art/ascender.jpg"),
  "Warkeeper": require("../../assets/titan-art/warkeeper.jpg"),
  "Talespinner": require("../../assets/titan-art/talespinner.jpg"),
};

export function titanArtwork(face: CardFace | null | undefined): ImageSourcePropType | undefined {
  return face?.kind === 'titan' ? images[isDreamwalker(face) ? 'Dreamwalker' : face.name] : undefined;
}
