"""Extract artwork-only Titan crops from reviewed original scans, without reconstruction.

python3 scripts/extract-titan-art.py
Config records source hashes and full-resolution crop rectangles. Existing
assets remain usable when archived sources are no longer present.
"""
from pathlib import Path
import hashlib
import json
import struct
import subprocess
import zlib

ROOT = Path(__file__).resolve().parents[1]
config = json.loads((ROOT / 'data/reference/titan-art-originals.json').read_text())
for item in config['images']:
    source = (ROOT / item['source']).resolve()
    target = ROOT / item['image']
    if not source.exists():
        assert target.exists(), f'Restore source scan: {source}'
        continue
    assert hashlib.sha256(source.read_bytes()).hexdigest() == item['sourceSha256'], f'Scan changed: {source.name}'
    decoded = subprocess.run(['djpeg', str(source)], check=True, capture_output=True).stdout
    header, rgb = decoded.split(b'\n255\n', 1)
    width, height = map(int, header.splitlines()[1].split())
    left, top, right, bottom = item['cropLTRB']
    assert len(rgb) == width * height * 3 and 0 <= left < right <= width and 0 <= top < bottom <= height
    pixels = b''.join(b'\0' + rgb[(y * width + left) * 3:(y * width + right) * 3] for y in range(top, bottom))
    def chunk(tag, data):
        return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff)
    target.parent.mkdir(parents=True, exist_ok=True)
    archive = (ROOT / item['archive']).resolve()
    archive.parent.mkdir(parents=True, exist_ok=True)
    archive.write_bytes(b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', right-left, bottom-top, 8, 2, 0, 0, 0))
                       + chunk(b'IDAT', zlib.compress(pixels, 9)) + chunk(b'IEND', b''))
    # Preserve the exact PNG crop in the artwork archive; ship a smaller full-resolution JPEG.
    cropped = b''.join(rgb[(y * width + left) * 3:(y * width + right) * 3] for y in range(top, bottom))
    ppm = f'P6\n{right-left} {bottom-top}\n255\n'.encode() + cropped
    target.write_bytes(subprocess.run(['cjpeg', '-quality', '92', '-optimize'], input=ppm, check=True, capture_output=True).stdout)

registry = ['// Generated by scripts/extract-titan-art.py; original artwork pixels are preserved.',
            "import type { ImageSourcePropType } from 'react-native';", "import type { CardFace } from '../domain/cards';",
            "import { isDreamwalker } from '../domain/titan-selection';", '',
            'const images: Record<string, ImageSourcePropType> = {']
for item in config['images']:
    registry.append(f'  {json.dumps(item["name"])}: require({json.dumps("../../" + item["image"])}),')
registry += ['};', '', 'export function titanArtwork(face: CardFace | null | undefined): ImageSourcePropType | undefined {',
             "  return face?.kind === 'titan' ? images[isDreamwalker(face) ? 'Dreamwalker' : face.name] : undefined;", '}', '']
(ROOT / 'src/theme/titan-art.ts').write_text('\n'.join(registry))
print(f'{len(config["images"])} full-resolution Titan illustrations registered')
