"""Embed the existing ATCC symbols used by Titan and Pattern tables.

Run from the app root: python3 scripts/import-pattern-icons.py
Original SVGs remain unchanged in ../ato_docs/images.
"""
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / 'ato_docs' / 'images'
TRAUMA = {'Minor', 'Major', 'Grave', 'Obol'}
KRATOS = {
    'AISuppress', 'BPSuppress', 'Black', 'Break', 'Burden', 'Closing', 'Clutch',
    'Diversion', 'Elation', 'Fire', 'GreaterPass', 'Heartseeker', 'Hope', 'Inspire',
    'Motivate', 'Opening', 'Overbreak', 'Pass', 'PolePosition', 'Power', 'Precise',
    'Provoke', 'Pushback', 'RedPowerDie', 'Reposition',
    'PowerReroll', 'Rouse', 'Scale', 'Succor', 'Taint', 'Tireless', 'Truth',
    'Unburden', 'Vault',
}


def invert(colour):
    if colour in {'black', 'white'}:
        return 'white' if colour == 'black' else 'black'
    if re.fullmatch(r'#[0-9a-fA-F]{3,8}', colour):
        value = colour[1:]
        if len(value) == 3:
            value = ''.join(c * 2 for c in value)
        if len(value) in {6, 8}:
            return '#' + ''.join(f'{255 - int(value[i:i+2], 16):02x}' for i in (0, 2, 4)) + value[6:]
    return colour


def clean(element, inverted):
    for child in list(element):
        tag = child.tag.rsplit('}', 1)[-1]
        if tag in {'namedview', 'metadata'} or 'display:none' in child.get('style', '').replace(' ', '') or child.get('display') == 'none':
            element.remove(child)
        else:
            clean(child, inverted)
    element.tag = element.tag.rsplit('}', 1)[-1]
    for key in list(element.attrib):
        if key.startswith('{') or key in {'id', 'version'}:
            del element.attrib[key]
    if 'style' in element.attrib:
        for declaration in element.attrib.pop('style').split(';'):
            if ':' not in declaration:
                continue
            key, value = declaration.split(':', 1)
            if key.strip() in {'fill', 'fill-opacity', 'fill-rule', 'stroke', 'stroke-width', 'stroke-opacity', 'stroke-linecap', 'stroke-linejoin', 'stroke-miterlimit', 'stroke-dasharray', 'opacity', 'display'}:
                element.set(key.strip(), value.strip())
    if inverted:
        for key in ('fill', 'stroke'):
            if key in element.attrib:
                element.set(key, invert(element.attrib[key]))


icons = {}
for name in sorted(TRAUMA | KRATOS):
    root = ET.parse(SOURCE / f'{name}.svg').getroot()
    # ATCC leaves coloured Power dice intact; CSS inverts the other Kratos icons.
    inverted = name in KRATOS and name != 'RedPowerDie'
    clean(root, inverted)
    if inverted and 'fill' not in root.attrib:
        # SVG's implicit black fill also participates in ATCC's CSS inversion.
        root.set('fill', '#ffffff')
    root.set('xmlns', 'http://www.w3.org/2000/svg')
    root.attrib.pop('width', None)
    root.attrib.pop('height', None)
    assert root.get('viewBox'), name
    assert not any(element.tag == 'image' for element in root.iter()), f'Visible raster image in {name}'
    icons[name] = ET.tostring(root, encoding='unicode')

output = '// Generated by scripts/import-pattern-icons.py from existing ATCC SVGs.\n'
output += '// Trauma colours and coloured dice are preserved; Kratos monochrome symbols are inverted.\n'
output += 'export const patternIcons = ' + json.dumps(icons, ensure_ascii=False, indent=2) + ' as const;\n'
(ROOT / 'src/theme/pattern-icons.ts').write_text(output)
print(f'Embedded {len(icons)} symbols ({len(output.encode())} bytes); hidden tracing images and editor metadata removed.')
