"""Embed SVGs used by Gear and the bundled keyword definitions.

Run from the app root. Originals in ../ato_docs remain unchanged.
Missing semantic names are reported and rendered as readable text at runtime.
"""
import hashlib
import json
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT.parent / 'ato_docs'
NAMES = {'Gear', 'd10', 'Condition', 'Reaction', 'OneHanded', 'TwoHanded', 'ThreeHanded', 'TwoOneHanded', 'ThreeOneHanded', 'Support', 'Attachment', 'Armor', 'Power', 'Precision', 'Speed'}
ALIASES = {'1 Hand': 'OneHanded', '2 Hands': 'TwoHanded', '3 Hands': 'ThreeHanded', '2 1 Hands': 'TwoOneHanded', '3 1 Hands': 'ThreeOneHanded', 'Labyrinth': 'Labyrinthians', 'AdversaryActivation': 'Adversary'}
for colour in ('Red', 'Black', 'White', 'Mortal'):
    for kind in ('Power', 'Armor'):
        for prefix in ('', 'Reversed'):
            NAMES.add(f'{prefix}{colour}{kind}Die')
NAMES.update({'EvasionReroll', 'PowerReroll', 'LaserResistance', 'MicrowaveResistance', 'InvertedDoom', 'InvertedProgress'})
NAMES.update({'StructuralTech', 'CombatTech', 'City', 'ArgoKnowledge', 'ArgoFate'})


def visit(value):
    if isinstance(value, list):
        for child in value:
            visit(child)
    elif isinstance(value, dict):
        if value.get('type') == 'icon' and isinstance(value.get('value'), str):
            NAMES.add(value['value'])
        for field in ('gate', 'gate2'):
            if isinstance(value.get(field), str):
                NAMES.add(ALIASES.get(value[field], value[field]))
        if isinstance(value.get('costs'), list):
            NAMES.update(value['costs'])
        for child in value.values():
            visit(child)


catalogue = json.loads((ROOT / 'data/generated/catalogue.json').read_text())
for card in catalogue['cards']:
    for face in card['faces']:
        if face['kind'] == 'gear':
            visit(face['data'])
            for stat in face['data']['defensiveStatistics']:
                NAMES.add(ALIASES.get(stat.get('type'), stat.get('type', '')))
        elif face['family'] == 'Technology':
            visit(face['data'])
for filename in ('keywords.json', 'titanAbilityData.json', 'primordialAbilityData.json'):
    visit(json.loads((ROOT / 'data/reference' / filename).read_text()))


def clean(element):
    for child in list(element):
        tag = child.tag.rsplit('}', 1)[-1]
        if tag in {'namedview', 'metadata', 'title', 'desc'} or 'display:none' in child.get('style', '').replace(' ', '') or child.get('display') == 'none':
            element.remove(child)
        else:
            clean(child)
    element.tag = element.tag.rsplit('}', 1)[-1]
    for key in list(element.attrib):
        if key.startswith('{'):
            value = element.attrib.pop(key)
            if key.endswith('}href'):
                element.set('href', value)
        elif key == 'version':
            del element.attrib[key]
    if 'style' in element.attrib:
        for declaration in element.attrib.pop('style').split(';'):
            if ':' not in declaration:
                continue
            key, value = declaration.split(':', 1)
            if key.strip() in {'fill', 'fill-opacity', 'fill-rule', 'stroke', 'stroke-width', 'stroke-opacity', 'stroke-linecap', 'stroke-linejoin', 'stroke-miterlimit', 'stroke-dasharray', 'opacity', 'display', 'clip-path', 'filter'}:
                element.set(key.strip(), value.strip())


icons, sources, missing = {}, [], []
for name in sorted(NAMES - {''}):
    path = DOCS / 'card-design/assets' / f'{name}.svg'
    if not path.exists():
        path = DOCS / 'images' / f'{name}.svg'
    if not path.exists():
        missing.append(name)
        continue
    root = ET.parse(path).getroot()
    clean(root)
    root.set('xmlns', 'http://www.w3.org/2000/svg')
    root.attrib.pop('width', None)
    root.attrib.pop('height', None)
    assert root.get('viewBox'), name
    assert not any(element.tag == 'image' for element in root.iter()), f'Visible raster image in {name}'
    icons[name] = ET.tostring(root, encoding='unicode')
    sources.append({'name': name, 'file': str(path.relative_to(DOCS)), 'sha256': hashlib.sha256(path.read_bytes()).hexdigest()})

output = '// Generated by scripts/import-gear-icons.py. Original colours and visible SVG geometry preserved.\n'
output += 'export const gearIcons: Readonly<Record<string, string>> = ' + json.dumps(icons, ensure_ascii=False, indent=2) + ';\n'
(ROOT / 'src/theme/gear-icons.ts').write_text(output)
(ROOT / 'data/reference/gear-asset-manifest.json').write_text(json.dumps({'sources': sources, 'missing': missing}, indent=2) + '\n')
print(f'Embedded {len(icons)} SVGs ({len(output.encode())} bytes). Readable fallbacks: {", ".join(missing)}')
