"""Bundle existing faction SVGs matching the five supplied diplomacy screenshots.

Run from the app root: python3 scripts/import-diplomacy-icons.py
Sources in ../ato_docs/images are preserved. No screenshot tracing is needed.
"""
import json
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / 'ato_docs' / 'images'
NAMES = [
    'Minoans', 'Labyrinthians', 'Hornsworn', 'Helots', 'Cyclopes', 'Symmachy',
    'Sunheirs', 'Delphians', 'TwilightWatch', 'Aristotelians', 'Wasters',
    'CloudThieves', 'OutcastVanguard', 'FollowersofArete', 'CycladeanProtectorate',
]


def clean(element):
    for child in list(element):
        tag = child.tag.rsplit('}', 1)[-1]
        if tag in {'namedview', 'metadata'} or 'display:none' in child.get('style', '').replace(' ', '') or child.get('display') == 'none':
            element.remove(child)
        else:
            clean(child)
    element.tag = element.tag.rsplit('}', 1)[-1]
    for key in list(element.attrib):
        if key.startswith('{') or key in {'id', 'version'}:
            del element.attrib[key]
    for declaration in element.attrib.pop('style', '').split(';'):
        if ':' not in declaration:
            continue
        key, value = declaration.split(':', 1)
        if key.strip() in {'fill', 'fill-opacity', 'fill-rule', 'stroke', 'stroke-width', 'stroke-opacity', 'stroke-linecap', 'stroke-linejoin', 'stroke-miterlimit', 'stroke-dasharray', 'opacity', 'display'}:
            element.set(key.strip(), value.strip())


icons = {}
for name in NAMES:
    root = ET.parse(SOURCE / f'{name}.svg').getroot()
    clean(root)
    root.set('xmlns', 'http://www.w3.org/2000/svg')
    root.attrib.pop('width', None)
    root.attrib.pop('height', None)
    assert root.get('viewBox'), name
    assert not any(element.tag == 'image' for element in root.iter()), f'Visible raster image in {name}'
    icons[name] = ET.tostring(root, encoding='unicode')

output = '// Generated by scripts/import-diplomacy-icons.py from existing ATCC faction SVGs.\n'
output += 'export const diplomacyIcons = ' + json.dumps(icons, ensure_ascii=False, indent=2) + ' as const;\n'
(ROOT / 'src/theme/diplomacy-icons.ts').write_text(output)
print(f'Embedded {len(icons)} faction symbols ({len(output.encode())} bytes).')
