// Generated by scripts/extract-gear-art.py; keyed by persistent definition and face IDs.
import type { GearArtwork } from '../domain/cards.ts';

export const gearArtwork: Readonly<Record<string, Partial<Record<'front' | 'back', GearArtwork>>>> = {
  "def_61558188902e56ca96781073": {
    "front": {
      "image": "assets/gear-art/cycle2-a/mazed-cestus.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/mazed-cestus.png",
      "width": 488,
      "height": 728,
      "artBottom": 468
    }
  },
  "def_ac6cc275dc91216e75e05000": {
    "front": {
      "image": "assets/gear-art/cycle2-a/temenos-scale-shield.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/temenos-scale-shield.png",
      "width": 486,
      "height": 728,
      "artBottom": 448
    },
    "back": {
      "image": "assets/gear-art/cycle2-a/temenos-scale-umbrella.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/temenos-scale-umbrella.png",
      "width": 504,
      "height": 745,
      "artBottom": 429
    }
  },
  "def_c5f40c37c8abd0f63325448f": {
    "front": {
      "image": "assets/gear-art/cycle2-a/temenos-xiphos.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/temenos-xiphos.png",
      "width": 488,
      "height": 728,
      "artBottom": 521
    },
    "back": {
      "image": "assets/gear-art/cycle2-a/temenos-whip.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/temenos-whip.png",
      "width": 487,
      "height": 728,
      "artBottom": 438
    }
  },
  "def_5b660ac8bbf14eeaf479685a": {
    "front": {
      "image": "assets/gear-art/cycle2-a/puzzle-axe.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/puzzle-axe.png",
      "width": 490,
      "height": 728,
      "artBottom": 524
    }
  },
  "def_8a4a927fa3501e20e64debae": {
    "front": {
      "image": "assets/gear-art/cycle2-a/labyrinth-mauler.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/labyrinth-mauler.png",
      "width": 487,
      "height": 728,
      "artBottom": 460
    }
  },
  "def_63677eb8093f4b86a3e7a586": {
    "front": {
      "image": "assets/gear-art/cycle2-a/labyrinth-armor.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/labyrinth-armor.png",
      "width": 470,
      "height": 728,
      "artBottom": 409
    }
  },
  "def_560add20be9cf8399e99dc79": {
    "front": {
      "image": "assets/gear-art/cycle2-a/scale-chakram.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/scale-chakram.png",
      "width": 485,
      "height": 745,
      "artBottom": 446
    }
  },
  "def_e341257ffb5fe8bfb2e80ed5": {
    "front": {
      "image": "assets/gear-art/cycle2-a/mazechute.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/mazechute.png",
      "width": 482,
      "height": 745,
      "artBottom": 434
    }
  },
  "def_d37dbc8fdc104b4cbaa96fc0": {
    "back": {
      "image": "assets/gear-art/cycle2-a/pseudomidion.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/pseudomidion.png",
      "width": 483,
      "height": 745,
      "artBottom": 554
    },
    "front": {
      "image": "assets/gear-art/cycle2-a/longinus.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/longinus.png",
      "width": 486,
      "height": 745,
      "artBottom": 469
    }
  },
  "def_148586339664a76b23490970": {
    "front": {
      "image": "assets/gear-art/cycle2-a/mazegma.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/mazegma.png",
      "width": 485,
      "height": 745,
      "artBottom": 445
    }
  },
  "def_b12bd681320ce723c4e8e6c6": {
    "front": {
      "image": "assets/gear-art/cycle2-a/stonewall.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/stonewall.png",
      "width": 471,
      "height": 745,
      "artBottom": 446
    }
  },
  "def_f27a1484fa260d51ca3ef40a": {
    "front": {
      "image": "assets/gear-art/cycle2-a/ambrostilts.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/ambrostilts.png",
      "width": 500,
      "height": 759,
      "artBottom": 514
    }
  },
  "def_6f01f1e8ad627539efbaa47c": {
    "front": {
      "image": "assets/gear-art/cycle2-a/amphoras-belt.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/amphoras-belt.png",
      "width": 485,
      "height": 759,
      "artBottom": 460
    }
  },
  "def_11163aef562fe4505b980329": {
    "front": {
      "image": "assets/gear-art/cycle2-a/isokratos-limiter.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/isokratos-limiter.png",
      "width": 481,
      "height": 759,
      "artBottom": 427
    }
  },
  "def_072b6e2a95e6c76278877983": {
    "front": {
      "image": "assets/gear-art/cycle2-a/stepping-stone.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/stepping-stone.png",
      "width": 487,
      "height": 759,
      "artBottom": 375
    }
  },
  "def_459ec46e5862daf2ef2ae00f": {
    "front": {
      "image": "assets/gear-art/cycle2-a/repurposed-cryptex.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/repurposed-cryptex.png",
      "width": 487,
      "height": 759,
      "artBottom": 427
    }
  },
  "def_d57bf501fdfa02a89d66518c": {
    "front": {
      "image": "assets/gear-art/cycle2-a/conqueror-nail.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/conqueror-nail.png",
      "width": 486,
      "height": 759,
      "artBottom": 354
    }
  },
  "def_ab4951636e0ce3c72b9279cb": {
    "front": {
      "image": "assets/gear-art/cycle2-a/pursuer-ultimatum.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/pursuer-ultimatum.png",
      "width": 470,
      "height": 759,
      "artBottom": 591
    }
  },
  "def_b8957a092c2c3350354ac51b": {
    "front": {
      "image": "assets/gear-art/epson-105748/sirenblade.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/sirenblade.png",
      "width": 492,
      "height": 730,
      "artBottom": 592
    }
  },
  "def_a035d24b1a379370df47f1ba": {
    "front": {
      "image": "assets/gear-art/epson-105748/boatmace.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/boatmace.png",
      "width": 486,
      "height": 730,
      "artBottom": 530
    }
  },
  "def_8d23e1cabdf1256d01f920a3": {
    "front": {
      "image": "assets/gear-art/epson-105748/kratos-kopis.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/kratos-kopis.png",
      "width": 454,
      "height": 730,
      "artBottom": 530
    }
  },
  "def_3c0b7969e25b0b0199a06bd3": {
    "front": {
      "image": "assets/gear-art/epson-105748/shipwrecker-shield.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/shipwrecker-shield.png",
      "width": 484,
      "height": 730,
      "artBottom": 564
    }
  },
  "def_3e19edef63981f07d536ddbb": {
    "front": {
      "image": "assets/gear-art/epson-105748/sail-camo.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/sail-camo.png",
      "width": 484,
      "height": 730,
      "artBottom": 426
    }
  },
  "def_dd70bd7bc6df7d486f6bb2dd": {
    "front": {
      "image": "assets/gear-art/epson-105748/tackle-sheath.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/tackle-sheath.png",
      "width": 487,
      "height": 730,
      "artBottom": 305
    }
  },
  "def_c6923c7aa6f687df11c5e135": {
    "front": {
      "image": "assets/gear-art/epson-105748/sail-spolas.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/sail-spolas.png",
      "width": 481,
      "height": 730,
      "artBottom": 568
    }
  },
  "def_78e420f19b3fc645e129a461": {
    "front": {
      "image": "assets/gear-art/epson-105748/iapetus-lifeguard.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/iapetus-lifeguard.png",
      "width": 491,
      "height": 750,
      "artBottom": 540
    }
  },
  "def_f62a818d125939d126bc2a1f": {
    "front": {
      "image": "assets/gear-art/epson-105748/ballista-gun.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/ballista-gun.png",
      "width": 480,
      "height": 747,
      "artBottom": 448
    }
  },
  "def_241caec1b63497a48ec9aa3b": {
    "front": {
      "image": "assets/gear-art/epson-105748/petrified-javelin.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/petrified-javelin.png",
      "width": 483,
      "height": 747,
      "artBottom": 604
    }
  },
  "def_db47d7e5872e7ec33d30250b": {
    "front": {
      "image": "assets/gear-art/epson-105748/siren-shield.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/siren-shield.png",
      "width": 483,
      "height": 747,
      "artBottom": 550
    }
  },
  "def_a3bc2021b4b453c3e42fbe0b": {
    "front": {
      "image": "assets/gear-art/epson-105748/siren-panoply-armor.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/siren-panoply-armor.png",
      "width": 484,
      "height": 747,
      "artBottom": 582
    }
  },
  "def_b82caa233e714012200a133d": {
    "front": {
      "image": "assets/gear-art/epson-105748/ancient-siren-panoply-armor.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/ancient-siren-panoply-armor.png",
      "width": 483,
      "height": 747,
      "artBottom": 588
    }
  },
  "def_2e19eb905c5e258dd31be205": {
    "front": {
      "image": "assets/gear-art/epson-105748/sirenteeth.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/sirenteeth.png",
      "width": 483,
      "height": 747,
      "artBottom": 577
    }
  },
  "def_74d6fea2292e207031ddfac0": {
    "front": {
      "image": "assets/gear-art/epson-105748/stabilizers.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/stabilizers.png",
      "width": 485,
      "height": 754,
      "artBottom": 410
    }
  },
  "def_67d2e489f63ec9910a7ddc08": {
    "front": {
      "image": "assets/gear-art/epson-105748/great-tree-club.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/great-tree-club.png",
      "width": 487,
      "height": 750,
      "artBottom": 573
    }
  },
  "def_cb67f79bd7632c8c06d89ec1": {
    "front": {
      "image": "assets/gear-art/epson-105748/whale-knives.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/whale-knives.png",
      "width": 485,
      "height": 745,
      "artBottom": 514
    }
  },
  "def_8f997a462c10907119ee1ba0": {
    "front": {
      "image": "assets/gear-art/epson-105748/teeth-khopesh.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/teeth-khopesh.png",
      "width": 484,
      "height": 745,
      "artBottom": 648
    }
  },
  "def_db7bd8e9aa70542fe0a232c9": {
    "front": {
      "image": "assets/gear-art/epson-105748/spring-harness.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/spring-harness.png",
      "width": 487,
      "height": 749,
      "artBottom": 551
    }
  },
  "def_b1846d413cc85d650e899753": {
    "front": {
      "image": "assets/gear-art/epson-105748/makesheath.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/makesheath.png",
      "width": 484,
      "height": 745,
      "artBottom": 511
    }
  },
  "def_e40ab8d533de288af01db102": {
    "front": {
      "image": "assets/gear-art/epson-105748/ares-aulos.png",
      "grayscaleImage": "assets/gear-art/epson-105748/grayscale/ares-aulos.png",
      "width": 472,
      "height": 745,
      "artBottom": 539
    }
  },
  "def_69349c7d961f6be3772b15b3": {
    "front": {
      "image": "assets/gear-art/epson-110215/jawbone-axe.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/jawbone-axe.png",
      "width": 486,
      "height": 730,
      "artBottom": 466
    }
  },
  "def_63472730bfeee66f1f1b40af": {
    "front": {
      "image": "assets/gear-art/epson-110215/analyticos-module.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/analyticos-module.png",
      "width": 486,
      "height": 730,
      "artBottom": 483
    }
  },
  "def_3948cd4a98c2a5415d18cf24": {
    "front": {
      "image": "assets/gear-art/epson-110215/impetus-breakers.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/impetus-breakers.png",
      "width": 485,
      "height": 730,
      "artBottom": 565
    }
  },
  "def_47d6d3c98167dbde2c77c579": {
    "front": {
      "image": "assets/gear-art/epson-110215/safety-rope.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/safety-rope.png",
      "width": 484,
      "height": 730,
      "artBottom": 543
    }
  },
  "def_434eeadfabb1d4771f957aa5": {
    "front": {
      "image": "assets/gear-art/epson-110215/primordial-lure.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/primordial-lure.png",
      "width": 485,
      "height": 730,
      "artBottom": 470
    }
  },
  "def_05098400b17549cbe7a088a0": {
    "front": {
      "image": "assets/gear-art/epson-110215/aeolipile-engine.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/aeolipile-engine.png",
      "width": 485,
      "height": 730,
      "artBottom": 397
    }
  },
  "def_133b24070b87d84c90a0d64c": {
    "front": {
      "image": "assets/gear-art/epson-110215/grappling-hook.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/grappling-hook.png",
      "width": 473,
      "height": 730,
      "artBottom": 499
    }
  },
  "def_50a6af6cd018aa9033cf99fd": {
    "front": {
      "image": "assets/gear-art/epson-110215/liontail-whip.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/liontail-whip.png",
      "width": 492,
      "height": 747,
      "artBottom": 458
    }
  },
  "def_b73e1947101203d9a9a4b81c": {
    "front": {
      "image": "assets/gear-art/epson-110215/longmast-spear.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/longmast-spear.png",
      "width": 486,
      "height": 747,
      "artBottom": 508
    }
  },
  "def_b895aa3655a51513d20bdce2": {
    "front": {
      "image": "assets/gear-art/epson-110215/hermes-tatters.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/hermes-tatters.png",
      "width": 485,
      "height": 747,
      "artBottom": 496
    }
  },
  "def_e975236904d97af23031f3c3": {
    "front": {
      "image": "assets/gear-art/epson-110215/mothlame.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/mothlame.png",
      "width": 484,
      "height": 747,
      "artBottom": 464
    }
  },
  "def_7a6baa4b125a04f69ba8bcef": {
    "front": {
      "image": "assets/gear-art/epson-110215/pursuer-imperative.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/pursuer-imperative.png",
      "width": 485,
      "height": 747,
      "artBottom": 581
    }
  },
  "def_043048383c1c7516476b3664": {
    "front": {
      "image": "assets/gear-art/epson-110215/naval-ram.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/naval-ram.png",
      "width": 485,
      "height": 747,
      "artBottom": 519
    }
  },
  "def_27dd2160f29e4f618251e9a0": {
    "front": {
      "image": "assets/gear-art/epson-110215/heavy-kopis.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/heavy-kopis.png",
      "width": 473,
      "height": 747,
      "artBottom": 457
    }
  },
  "def_638c1e0031219748eb9f2305": {
    "front": {
      "image": "assets/gear-art/epson-110215/instinct-linothorax.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/instinct-linothorax.png",
      "width": 493,
      "height": 746,
      "artBottom": 546
    }
  },
  "def_98e3a22fc47f26006a471331": {
    "front": {
      "image": "assets/gear-art/epson-110215/smelted-aspis.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/smelted-aspis.png",
      "width": 489,
      "height": 746,
      "artBottom": 400
    }
  },
  "def_4655aff19d1e0da88e783827": {
    "front": {
      "image": "assets/gear-art/epson-110215/smelted-xiphos.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/smelted-xiphos.png",
      "width": 488,
      "height": 746,
      "artBottom": 585
    }
  },
  "def_d6eb05ebc03e46b73653cefd": {
    "front": {
      "image": "assets/gear-art/epson-110215/smelted-breastplate.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/smelted-breastplate.png",
      "width": 487,
      "height": 746,
      "artBottom": 458
    }
  },
  "def_d79254fa73a5796c07b057b2": {
    "front": {
      "image": "assets/gear-art/epson-110215/knuckle-shield.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/knuckle-shield.png",
      "width": 477,
      "height": 746,
      "artBottom": 418
    }
  },
  "def_f7c77a43c882cdec4b163cb7": {
    "front": {
      "image": "assets/gear-art/epson-110215/hekaton-panoply-armor.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/hekaton-panoply-armor.png",
      "width": 483,
      "height": 742,
      "artBottom": 414
    }
  },
  "def_e72023f732f783a9b6a146bd": {
    "front": {
      "image": "assets/gear-art/epson-110215/whalebone-bident.png",
      "grayscaleImage": "assets/gear-art/epson-110215/grayscale/whalebone-bident.png",
      "width": 474,
      "height": 742,
      "artBottom": 513
    }
  },
  "def_ddffa5e259c0964591d8b101": {
    "front": {
      "image": "assets/gear-art/epson-110738/gigan.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/gigan.png",
      "width": 487,
      "height": 732,
      "artBottom": 586
    }
  },
  "def_2e484acd500bb552149b1bcf": {
    "front": {
      "image": "assets/gear-art/epson-110738/maze-rake.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/maze-rake.png",
      "width": 483,
      "height": 732,
      "artBottom": 437
    }
  },
  "def_e6b499a4413aa8c421626944": {
    "front": {
      "image": "assets/gear-art/epson-110738/whaler-javelin.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/whaler-javelin.png",
      "width": 488,
      "height": 732,
      "artBottom": 490
    }
  },
  "def_dec8f7bb68a71c0bb79091b2": {
    "front": {
      "image": "assets/gear-art/epson-110738/hullbow.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/hullbow.png",
      "width": 489,
      "height": 732,
      "artBottom": 476
    }
  },
  "def_92a3b1b5608afef175edadc9": {
    "front": {
      "image": "assets/gear-art/epson-110738/ariadne-s-hello.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/ariadne-s-hello.png",
      "width": 489,
      "height": 732,
      "artBottom": 526
    }
  },
  "def_89c7d41636b225cdbab445e9": {
    "front": {
      "image": "assets/gear-art/epson-110738/morpheus-module.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/morpheus-module.png",
      "width": 485,
      "height": 732,
      "artBottom": 327
    }
  },
  "def_98dd4a0879022ac6c406e8a5": {
    "front": {
      "image": "assets/gear-art/epson-110738/bull-aspis.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/bull-aspis.png",
      "width": 474,
      "height": 735,
      "artBottom": 443
    }
  },
  "def_89d368e9790400b185be80d9": {
    "front": {
      "image": "assets/gear-art/epson-110738/ariadne-s-goodbye.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/ariadne-s-goodbye.png",
      "width": 488,
      "height": 746,
      "artBottom": 570
    }
  },
  "def_109ffcc7e3de5f88dcccfd3e": {
    "front": {
      "image": "assets/gear-art/epson-110738/mazemmer.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/mazemmer.png",
      "width": 486,
      "height": 746,
      "artBottom": 529
    }
  },
  "def_432153d343c8647f57e893f2": {
    "front": {
      "image": "assets/gear-art/epson-110738/gigas.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/gigas.png",
      "width": 487,
      "height": 746,
      "artBottom": 667
    }
  },
  "def_dbb19a86cf0bc8c638594cd5": {
    "front": {
      "image": "assets/gear-art/epson-110738/pillarmace.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/pillarmace.png",
      "width": 486,
      "height": 746,
      "artBottom": 588
    }
  },
  "def_33c6fbe9d86ba0ebd7c5ad66": {
    "front": {
      "image": "assets/gear-art/epson-110738/hekatomb.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/hekatomb.png",
      "width": 486,
      "height": 746,
      "artBottom": 616
    }
  },
  "def_a9cc21f7d2684ae8d2dd07f1": {
    "front": {
      "image": "assets/gear-art/epson-110738/rebound-hammer.png",
      "grayscaleImage": "assets/gear-art/epson-110738/grayscale/rebound-hammer.png",
      "width": 468,
      "height": 746,
      "artBottom": 588
    }
  },
  "def_7593d0b4bf8110c1ad5f3b1b": {
    "front": {
      "image": "assets/gear-art/epson-185551/the-end.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/the-end.png",
      "width": 488,
      "height": 728,
      "artBottom": 416
    }
  },
  "def_cbbaea3d406ef2ad2bca117e": {
    "front": {
      "image": "assets/gear-art/epson-185551/cowl-of-char.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/cowl-of-char.png",
      "width": 486,
      "height": 728,
      "artBottom": 452
    }
  },
  "def_b24030357b6872ed3f5ae1f5": {
    "front": {
      "image": "assets/gear-art/epson-185551/leg-khopesh.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/leg-khopesh.png",
      "width": 486,
      "height": 728,
      "artBottom": 551
    },
    "back": {
      "image": "assets/gear-art/epson-185936/leg-spear.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/leg-spear.png",
      "width": 481,
      "height": 728,
      "artBottom": 554
    }
  },
  "def_1b2072d55810e190a414d824": {
    "front": {
      "image": "assets/gear-art/epson-185551/jaws-of-the-lion.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/jaws-of-the-lion.png",
      "width": 486,
      "height": 728,
      "artBottom": 452
    }
  },
  "def_218341bb73ce6cac590b0ed3": {
    "front": {
      "image": "assets/gear-art/epson-185551/rememberance.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/rememberance.png",
      "width": 488,
      "height": 728,
      "artBottom": 441
    }
  },
  "def_08a2a8b6f7480d2577f618ec": {
    "front": {
      "image": "assets/gear-art/epson-185551/left-maulfist.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/left-maulfist.png",
      "width": 486,
      "height": 728,
      "artBottom": 475
    }
  },
  "def_a04ac642d0912d68abfcb027": {
    "front": {
      "image": "assets/gear-art/epson-185551/pyramidion.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/pyramidion.png",
      "width": 470,
      "height": 728,
      "artBottom": 346
    }
  },
  "def_16c33caeee4dade6154a0fb0": {
    "front": {
      "image": "assets/gear-art/epson-185551/pyrasklepios.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/pyrasklepios.png",
      "width": 488,
      "height": 746,
      "artBottom": 368
    }
  },
  "def_0bc0501138e81f84c4e7145b": {
    "front": {
      "image": "assets/gear-art/epson-185551/bellerophon.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/bellerophon.png",
      "width": 486,
      "height": 746,
      "artBottom": 587
    }
  },
  "def_941d85e059c6332f98740e47": {
    "front": {
      "image": "assets/gear-art/epson-185551/sisyphus-s-triumph.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/sisyphus-s-triumph.png",
      "width": 486,
      "height": 746,
      "artBottom": 568
    }
  },
  "def_2501a268bf79dd0be63f027c": {
    "front": {
      "image": "assets/gear-art/epson-185551/sisyphus-s-burden.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/sisyphus-s-burden.png",
      "width": 486,
      "height": 746,
      "artBottom": 410
    }
  },
  "def_77ef5c3cc042bba35cef073f": {
    "front": {
      "image": "assets/gear-art/epson-185551/maw-of-byzantion.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/maw-of-byzantion.png",
      "width": 488,
      "height": 746,
      "artBottom": 425
    }
  },
  "def_55a4e6576f3ad53a9bc2cc39": {
    "front": {
      "image": "assets/gear-art/epson-185551/immeasurable-weight.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/immeasurable-weight.png",
      "width": 486,
      "height": 746,
      "artBottom": 441
    }
  },
  "def_7f7dfe080fad17e2e7cc123a": {
    "front": {
      "image": "assets/gear-art/epson-185551/context.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/context.png",
      "width": 470,
      "height": 746,
      "artBottom": 364
    }
  },
  "def_6f22dd77ba6af3a1cbf8c33e": {
    "front": {
      "image": "assets/gear-art/epson-185551/glimmer-shroud.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/glimmer-shroud.png",
      "width": 488,
      "height": 752,
      "artBottom": 470
    }
  },
  "def_77d387867a0e509a62b4f111": {
    "front": {
      "image": "assets/gear-art/epson-185551/mazemace.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/mazemace.png",
      "width": 486,
      "height": 752,
      "artBottom": 546
    }
  },
  "def_c63619973a9013610ed7cd28": {
    "front": {
      "image": "assets/gear-art/epson-185551/the-promise.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/the-promise.png",
      "width": 486,
      "height": 752,
      "artBottom": 524
    }
  },
  "def_f6a3fe4054b8ea729ab55e70": {
    "front": {
      "image": "assets/gear-art/epson-185551/shieldblade.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/shieldblade.png",
      "width": 486,
      "height": 752,
      "artBottom": 476
    }
  },
  "def_b361796bcae5527f1c4f391b": {
    "front": {
      "image": "assets/gear-art/epson-185551/fumeblade-barred.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/fumeblade-barred.png",
      "width": 488,
      "height": 752,
      "artBottom": 458
    },
    "back": {
      "image": "assets/gear-art/epson-185936/fumeblade-hidden.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/fumeblade-hidden.png",
      "width": 484,
      "height": 728,
      "artBottom": 495
    }
  },
  "def_9de365ee0910607a459485a4": {
    "front": {
      "image": "assets/gear-art/epson-185551/necrotic-virus.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/necrotic-virus.png",
      "width": 486,
      "height": 752,
      "artBottom": 409
    },
    "back": {
      "image": "assets/gear-art/epson-185936/necroxiphos.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/necroxiphos.png",
      "width": 472,
      "height": 728,
      "artBottom": 386
    }
  },
  "def_f3ab1e8e5ef3faf8b284e5fd": {
    "front": {
      "image": "assets/gear-art/epson-185551/elephantine-armor.png",
      "grayscaleImage": "assets/gear-art/epson-185551/grayscale/elephantine-armor.png",
      "width": 470,
      "height": 752,
      "artBottom": 404
    }
  },
  "def_29c7896602864388351ceb18": {
    "front": {
      "image": "assets/gear-art/epson-185936/nail-spear.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/nail-spear.png",
      "width": 511,
      "height": 728,
      "artBottom": 502
    }
  },
  "def_42a3c8341115ecf7a4507114": {
    "front": {
      "image": "assets/gear-art/epson-185936/medusalem.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/medusalem.png",
      "width": 479,
      "height": 728,
      "artBottom": 411
    }
  },
  "def_352b91fe59bba1131fbf8cc4": {
    "front": {
      "image": "assets/gear-art/epson-185936/minohead.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/minohead.png",
      "width": 477,
      "height": 728,
      "artBottom": 423
    }
  },
  "def_836beb266bdf6399d38072e3": {
    "front": {
      "image": "assets/gear-art/epson-185936/theseus-s-razor.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/theseus-s-razor.png",
      "width": 486,
      "height": 728,
      "artBottom": 407
    }
  },
  "def_20611bd46d2f4780f81fc0db": {
    "front": {
      "image": "assets/gear-art/epson-185936/muck-virus.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/muck-virus.png",
      "width": 511,
      "height": 743,
      "artBottom": 470
    }
  },
  "def_94484f10d318031603efc335": {
    "front": {
      "image": "assets/gear-art/epson-185936/unseen-scar.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/unseen-scar.png",
      "width": 479,
      "height": 743,
      "artBottom": 355
    }
  },
  "def_328b720fc85197630dea83bb": {
    "front": {
      "image": "assets/gear-art/epson-185936/archon-pauldron.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/archon-pauldron.png",
      "width": 477,
      "height": 743,
      "artBottom": 483
    }
  },
  "def_8af6234f733defcb3f48aa1a": {
    "front": {
      "image": "assets/gear-art/epson-185936/mazey-the-labyrinthian-dog.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/mazey-the-labyrinthian-dog.png",
      "width": 481,
      "height": 743,
      "artBottom": 321
    }
  },
  "def_465127c698264ea196c30937": {
    "front": {
      "image": "assets/gear-art/epson-185936/unsolved-enigma.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/unsolved-enigma.png",
      "width": 484,
      "height": 743,
      "artBottom": 327
    }
  },
  "def_786b1249d8ce53789bb24b89": {
    "front": {
      "image": "assets/gear-art/epson-185936/manos-discus.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/manos-discus.png",
      "width": 472,
      "height": 743,
      "artBottom": 520
    }
  },
  "def_2b43196e87b4a1aa864c2cb9": {
    "front": {
      "image": "assets/gear-art/epson-185936/icarus-lot.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/icarus-lot.png",
      "width": 511,
      "height": 760,
      "artBottom": 529
    }
  },
  "def_cce73c5823bf1f5389c40c78": {
    "front": {
      "image": "assets/gear-art/epson-185936/spherecast.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/spherecast.png",
      "width": 479,
      "height": 760,
      "artBottom": 407
    },
    "back": {
      "image": "assets/gear-art/epson-212452/searing-pillar.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/searing-pillar.png",
      "width": 479,
      "height": 727,
      "artBottom": 457
    }
  },
  "def_9b1af92a9ccefb117c9cd7d4": {
    "front": {
      "image": "assets/gear-art/epson-185936/right-talon-of-doom.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/right-talon-of-doom.png",
      "width": 477,
      "height": 760,
      "artBottom": 531
    },
    "back": {
      "image": "assets/gear-art/epson-212452/icarian-katar.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/icarian-katar.png",
      "width": 489,
      "height": 727,
      "artBottom": 416
    }
  },
  "def_e3c7b8da2ae35687dba0ceab": {
    "front": {
      "image": "assets/gear-art/epson-185936/paradox.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/paradox.png",
      "width": 486,
      "height": 760,
      "artBottom": 531
    }
  },
  "def_dd5546747028e5bf67dbe2c8": {
    "front": {
      "image": "assets/gear-art/epson-185936/eye-of-the-watcher.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/eye-of-the-watcher.png",
      "width": 481,
      "height": 760,
      "artBottom": 479
    }
  },
  "def_c327d4f5260c6a18037bfdb9": {
    "front": {
      "image": "assets/gear-art/epson-185936/ambramat-armor.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/ambramat-armor.png",
      "width": 484,
      "height": 760,
      "artBottom": 495
    }
  },
  "def_0e707a0bab686ce29c601ba1": {
    "front": {
      "image": "assets/gear-art/epson-185936/umbral-virus.png",
      "grayscaleImage": "assets/gear-art/epson-185936/grayscale/umbral-virus.png",
      "width": 472,
      "height": 760,
      "artBottom": 486
    },
    "back": {
      "image": "assets/gear-art/epson-212452/umbral-carapace.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/umbral-carapace.png",
      "width": 470,
      "height": 727,
      "artBottom": 434
    }
  },
  "def_3b6bf24413178ff91c4a0f21": {
    "front": {
      "image": "assets/gear-art/epson-210624/great-breaker.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/great-breaker.png",
      "width": 484,
      "height": 727,
      "artBottom": 484
    }
  },
  "def_c9381d7b0670cd2782532f6f": {
    "front": {
      "image": "assets/gear-art/epson-210624/impact-armor.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/impact-armor.png",
      "width": 486,
      "height": 727,
      "artBottom": 458
    }
  },
  "def_39fb71e037825c0881e5fe3a": {
    "front": {
      "image": "assets/gear-art/epson-210624/collision-shield.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/collision-shield.png",
      "width": 488,
      "height": 727,
      "artBottom": 494
    }
  },
  "def_565980ba3dd68ac1a19f6ba0": {
    "front": {
      "image": "assets/gear-art/epson-210624/iapetus-lifesaver.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/iapetus-lifesaver.png",
      "width": 484,
      "height": 727,
      "artBottom": 526
    }
  },
  "def_4f67dc040937547c288750f4": {
    "front": {
      "image": "assets/gear-art/epson-210624/achillean-hectors.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/achillean-hectors.png",
      "width": 484,
      "height": 727,
      "artBottom": 441
    }
  },
  "def_3c014172da91bf78d6cfb2e8": {
    "front": {
      "image": "assets/gear-art/epson-210624/boost-kothornos.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/boost-kothornos.png",
      "width": 484,
      "height": 727,
      "artBottom": 494
    }
  },
  "def_e3d3918978496f6da2662f4f": {
    "front": {
      "image": "assets/gear-art/epson-210624/control-module.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/control-module.png",
      "width": 473,
      "height": 727,
      "artBottom": 467
    }
  },
  "def_23b991706c979449431a4f08": {
    "front": {
      "image": "assets/gear-art/epson-210624/lethe-guard.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/lethe-guard.png",
      "width": 484,
      "height": 746,
      "artBottom": 376
    }
  },
  "def_dee1a57fa844368bba3473fd": {
    "front": {
      "image": "assets/gear-art/epson-210624/asklepios-node.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/asklepios-node.png",
      "width": 486,
      "height": 746,
      "artBottom": 519
    }
  },
  "def_cdddf6feacb4a21fdc5724fc": {
    "front": {
      "image": "assets/gear-art/epson-210624/covenant.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/covenant.png",
      "width": 489,
      "height": 746,
      "artBottom": 420
    }
  },
  "def_d3f2c8ebc688e9de114aada2": {
    "front": {
      "image": "assets/gear-art/epson-210624/siegetower-pauldron.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/siegetower-pauldron.png",
      "width": 488,
      "height": 746,
      "artBottom": 420
    }
  },
  "def_74865d39073e1119ee52d29d": {
    "front": {
      "image": "assets/gear-art/epson-210624/watchtower-pauldron.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/watchtower-pauldron.png",
      "width": 486,
      "height": 746,
      "artBottom": 418
    }
  },
  "def_66c74d62c9da72087b81c6e2": {
    "front": {
      "image": "assets/gear-art/epson-210624/relief-cestus.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/relief-cestus.png",
      "width": 484,
      "height": 746,
      "artBottom": 496
    }
  },
  "def_e77b306d0dbfd7c7e8f398ac": {
    "front": {
      "image": "assets/gear-art/epson-210624/stone-relief-armor.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/stone-relief-armor.png",
      "width": 473,
      "height": 746,
      "artBottom": 511
    }
  },
  "def_024cb29f78198ec49342b34a": {
    "front": {
      "image": "assets/gear-art/epson-210624/grand-ramaxe.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/grand-ramaxe.png",
      "width": 484,
      "height": 745,
      "artBottom": 543
    }
  },
  "def_4d0d52e413f7d54ff269212b": {
    "front": {
      "image": "assets/gear-art/epson-210624/chain-whip.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/chain-whip.png",
      "width": 484,
      "height": 745,
      "artBottom": 547
    }
  },
  "def_4cfe7fa97cd49fbf87bb7735": {
    "front": {
      "image": "assets/gear-art/epson-210624/fireboat.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/fireboat.png",
      "width": 486,
      "height": 745,
      "artBottom": 566
    }
  },
  "def_dbb2d468ccb5bb63ebfb5ea7": {
    "front": {
      "image": "assets/gear-art/epson-210624/eviscerators.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/eviscerators.png",
      "width": 490,
      "height": 745,
      "artBottom": 518
    }
  },
  "def_044e1bc110fff9b60e0230f9": {
    "front": {
      "image": "assets/gear-art/epson-210624/vaulting-rope.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/vaulting-rope.png",
      "width": 486,
      "height": 745,
      "artBottom": 540
    }
  },
  "def_db711e05caf4d00fef758b0d": {
    "back": {
      "image": "assets/gear-art/epson-210624/metabow.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/metabow.png",
      "width": 486,
      "height": 745,
      "artBottom": 530
    },
    "front": {
      "image": "assets/gear-art/epson-210624/metasword.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/metasword.png",
      "width": 480,
      "height": 745,
      "artBottom": 604
    }
  },
  "def_54b6ba6736297a521535b8a9": {
    "front": {
      "image": "assets/gear-art/epson-211018/katarus.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/katarus.png",
      "width": 500,
      "height": 731,
      "artBottom": 516
    }
  },
  "def_d50974c7ea7812cfa76eb1d5": {
    "front": {
      "image": "assets/gear-art/epson-211018/muck-armor.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/muck-armor.png",
      "width": 489,
      "height": 731,
      "artBottom": 407
    }
  },
  "def_de2547f0a2fbda3870f6a647": {
    "back": {
      "image": "assets/gear-art/epson-211018/ladder-mode.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/ladder-mode.png",
      "width": 488,
      "height": 731,
      "artBottom": 403
    },
    "front": {
      "image": "assets/gear-art/epson-211018/ladder-buckler.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/ladder-buckler.png",
      "width": 476,
      "height": 731,
      "artBottom": 424
    }
  },
  "def_6e30e99b6d4b1a2eaf107e99": {
    "front": {
      "image": "assets/gear-art/epson-211018/muckbane.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/muckbane.png",
      "width": 485,
      "height": 731,
      "artBottom": 624
    }
  },
  "def_a64a5f0b6e29f97b7bcf520e": {
    "front": {
      "image": "assets/gear-art/epson-211018/cyclostus.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/cyclostus.png",
      "width": 472,
      "height": 731,
      "artBottom": 406
    }
  },
  "def_b8081b0e2ccba3a7797a579d": {
    "back": {
      "image": "assets/gear-art/epson-211018/boom-pole.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/boom-pole.png",
      "width": 499,
      "height": 743,
      "artBottom": 343
    },
    "front": {
      "image": "assets/gear-art/epson-211018/boom-spear.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/boom-spear.png",
      "width": 472,
      "height": 764,
      "artBottom": 535
    }
  },
  "def_6e9c85fc4e34e78d79c312c7": {
    "front": {
      "image": "assets/gear-art/epson-211018/muck-bludgeon.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/muck-bludgeon.png",
      "width": 490,
      "height": 743,
      "artBottom": 521
    }
  },
  "def_0e5cc0c028a1e6b02777c401": {
    "front": {
      "image": "assets/gear-art/epson-211018/dragon-bellow.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/dragon-bellow.png",
      "width": 486,
      "height": 743,
      "artBottom": 470
    }
  },
  "def_c664e37d1bccbf12f92532d1": {
    "front": {
      "image": "assets/gear-art/epson-211018/ambrosia-trocar.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/ambrosia-trocar.png",
      "width": 488,
      "height": 743,
      "artBottom": 545
    }
  },
  "def_785f5a7f4b5fac9edf01666c": {
    "front": {
      "image": "assets/gear-art/epson-211018/maulmace.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/maulmace.png",
      "width": 476,
      "height": 743,
      "artBottom": 517
    }
  },
  "def_6eb329f1f26c218f89699f3e": {
    "front": {
      "image": "assets/gear-art/epson-211018/needle-sword.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/needle-sword.png",
      "width": 485,
      "height": 743,
      "artBottom": 472
    }
  },
  "def_7d504be35f4966b43139cfa8": {
    "front": {
      "image": "assets/gear-art/epson-211018/vaulting-spear.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/vaulting-spear.png",
      "width": 472,
      "height": 743,
      "artBottom": 426
    }
  },
  "def_1d21790aa90c51fb97044897": {
    "front": {
      "image": "assets/gear-art/epson-211018/temple-camo.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/temple-camo.png",
      "width": 495,
      "height": 764,
      "artBottom": 420
    }
  },
  "def_3e04a88ca2ef6bc9505532d6": {
    "front": {
      "image": "assets/gear-art/epson-211018/faceshield.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/faceshield.png",
      "width": 492,
      "height": 764,
      "artBottom": 458
    }
  },
  "def_fc859c21e41ddbb4af93f5ad": {
    "front": {
      "image": "assets/gear-art/epson-211018/roll-breakers.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/roll-breakers.png",
      "width": 488,
      "height": 764,
      "artBottom": 512
    }
  },
  "def_f32459dfab4321815c42457e": {
    "front": {
      "image": "assets/gear-art/epson-211018/squat-armor.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/squat-armor.png",
      "width": 488,
      "height": 764,
      "artBottom": 442
    }
  },
  "def_d4e33a69642dc1688e9ec15e": {
    "front": {
      "image": "assets/gear-art/epson-211018/pithos-armor.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/pithos-armor.png",
      "width": 476,
      "height": 764,
      "artBottom": 456
    }
  },
  "def_5a32b9d80bddc54f78fc0e24": {
    "front": {
      "image": "assets/gear-art/epson-211018/chimeric-xiphos.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/chimeric-xiphos.png",
      "width": 485,
      "height": 764,
      "artBottom": 427
    }
  },
  "def_0eea196607c08352330a66d3": {
    "front": {
      "image": "assets/gear-art/epson-211609/carver-kopis.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/carver-kopis.png",
      "width": 491,
      "height": 734,
      "artBottom": 565
    }
  },
  "def_f01d60a752785a861b737dbc": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-totem.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-totem.png",
      "width": 484,
      "height": 734,
      "artBottom": 347
    }
  },
  "def_54acada1dd3d96d300f05c15": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-knives.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-knives.png",
      "width": 486,
      "height": 734,
      "artBottom": 468
    }
  },
  "def_8356a32e9d8389ef18c1600c": {
    "front": {
      "image": "assets/gear-art/epson-211609/spartan-kopis.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/spartan-kopis.png",
      "width": 487,
      "height": 734,
      "artBottom": 504
    }
  },
  "def_7953a7a5a42900ca3b7ebce9": {
    "front": {
      "image": "assets/gear-art/epson-211609/spartan-war-axe.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/spartan-war-axe.png",
      "width": 486,
      "height": 734,
      "artBottom": 557
    }
  },
  "def_a2b46c0958ba8e8204b629ca": {
    "front": {
      "image": "assets/gear-art/epson-211609/labyrinthization.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/labyrinthization.png",
      "width": 486,
      "height": 734,
      "artBottom": 408
    }
  },
  "def_8a8cad406c251d20a1eefad5": {
    "front": {
      "image": "assets/gear-art/epson-211609/medusa-extract.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/medusa-extract.png",
      "width": 464,
      "height": 734,
      "artBottom": 446
    }
  },
  "def_3f1413dba827ee88eefbe8c4": {
    "front": {
      "image": "assets/gear-art/epson-211609/heavy-spear.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/heavy-spear.png",
      "width": 484,
      "height": 760,
      "artBottom": 555
    }
  },
  "def_daf5328eb7b0499a62e07465": {
    "front": {
      "image": "assets/gear-art/epson-211609/gastraphetes.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/gastraphetes.png",
      "width": 486,
      "height": 760,
      "artBottom": 497
    }
  },
  "def_20ecd9e4ed4cf37856d0a0fc": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-khopesh.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-khopesh.png",
      "width": 487,
      "height": 760,
      "artBottom": 646
    }
  },
  "def_1e96a92c7288054dc7cdb7d0": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-forge-hammer.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-forge-hammer.png",
      "width": 486,
      "height": 760,
      "artBottom": 505
    }
  },
  "def_802be492d4e7d41a955bed97": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-visor.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-visor.png",
      "width": 486,
      "height": 760,
      "artBottom": 425
    }
  },
  "def_4a60bba7e035ddb3aa5a3097": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-linothorax.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-linothorax.png",
      "width": 464,
      "height": 760,
      "artBottom": 529
    }
  },
  "def_3b781cfb15a15d0e87b2720e": {
    "front": {
      "image": "assets/gear-art/epson-212452/phoenixiphos.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/phoenixiphos.png",
      "width": 495,
      "height": 727,
      "artBottom": 532
    }
  },
  "def_1f7474895f1381644f9d239c": {
    "front": {
      "image": "assets/gear-art/epson-212452/atlantean-oscillator.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/atlantean-oscillator.png",
      "width": 498,
      "height": 727,
      "artBottom": 502
    }
  },
  "def_cec2d1eb9712d9fb037fdf15": {
    "front": {
      "image": "assets/gear-art/epson-212452/future-cryptex.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/future-cryptex.png",
      "width": 488,
      "height": 727,
      "artBottom": 450
    }
  },
  "def_b8b1fc32093676aebe89eb51": {
    "front": {
      "image": "assets/gear-art/epson-212452/icarus-s-fall.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/icarus-s-fall.png",
      "width": 489,
      "height": 727,
      "artBottom": 600
    }
  },
  "def_4c53e8f8e46a93b767245fd3": {
    "front": {
      "image": "assets/gear-art/epson-212452/abyssal-watchers.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/abyssal-watchers.png",
      "width": 495,
      "height": 745,
      "artBottom": 295
    }
  },
  "def_c25b96d5744e5e884080bcc4": {
    "front": {
      "image": "assets/gear-art/epson-212452/smoldering-mace.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/smoldering-mace.png",
      "width": 498,
      "height": 745,
      "artBottom": 550
    }
  },
  "def_8899c629558eace84e5fcf72": {
    "front": {
      "image": "assets/gear-art/epson-212452/hardened-cestus.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/hardened-cestus.png",
      "width": 488,
      "height": 745,
      "artBottom": 482
    }
  },
  "def_b0cc0e8bbaaa7d34e26aeb4a": {
    "front": {
      "image": "assets/gear-art/epson-212452/theogonias.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/theogonias.png",
      "width": 489,
      "height": 745,
      "artBottom": 491
    }
  },
  "def_fcb5c672cef6353b17f45528": {
    "front": {
      "image": "assets/gear-art/epson-212452/shellusalem.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/shellusalem.png",
      "width": 479,
      "height": 745,
      "artBottom": 427
    }
  },
  "def_fff4d98806e9d8bf51f70e1a": {
    "front": {
      "image": "assets/gear-art/epson-212452/grandfather-s.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/grandfather-s.png",
      "width": 489,
      "height": 745,
      "artBottom": 539
    }
  },
  "def_38e068613d0931bb390a1619": {
    "front": {
      "image": "assets/gear-art/epson-212452/cyclopean-hand-mirror.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/cyclopean-hand-mirror.png",
      "width": 470,
      "height": 745,
      "artBottom": 464
    }
  },
  "def_d7d57d360572c4ee19f849c8": {
    "front": {
      "image": "assets/gear-art/epson-212452/abyss-mirror.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/abyss-mirror.png",
      "width": 495,
      "height": 757,
      "artBottom": 459
    }
  },
  "def_0af9860267539b8220cd24e9": {
    "front": {
      "image": "assets/gear-art/epson-212452/abyss-linothorax.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/abyss-linothorax.png",
      "width": 498,
      "height": 757,
      "artBottom": 548
    }
  },
  "def_0fbd571567855b09d2529aab": {
    "front": {
      "image": "assets/gear-art/epson-212452/abyss-thorax.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/abyss-thorax.png",
      "width": 488,
      "height": 757,
      "artBottom": 475
    }
  },
  "def_71b87cdfb2d096a8abbd60c2": {
    "front": {
      "image": "assets/gear-art/epson-212452/black-xiphos.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/black-xiphos.png",
      "width": 489,
      "height": 757,
      "artBottom": 563
    }
  },
  "def_8d9d75a640ed49b5801392ec": {
    "front": {
      "image": "assets/gear-art/epson-212452/black-javelin.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/black-javelin.png",
      "width": 479,
      "height": 757,
      "artBottom": 695
    }
  },
  "def_1c3548cd86755c5577b88f7a": {
    "front": {
      "image": "assets/gear-art/epson-212452/abyssal-spear.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/abyssal-spear.png",
      "width": 489,
      "height": 757,
      "artBottom": 432
    }
  },
  "def_7d73f5942afea8ddd9dea916": {
    "front": {
      "image": "assets/gear-art/epson-212452/excavated.png",
      "grayscaleImage": "assets/gear-art/epson-212452/grayscale/excavated.png",
      "width": 470,
      "height": 757,
      "artBottom": 418
    }
  },
  "def_969a315c1a3301b46f8894b7": {
    "front": {
      "image": "assets/gear-art/epson-213909/lightsword.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/lightsword.png",
      "width": 498,
      "height": 729,
      "artBottom": 462
    }
  },
  "def_9080d968cc2fade2355442e8": {
    "front": {
      "image": "assets/gear-art/epson-213909/believer-vestment.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/believer-vestment.png",
      "width": 485,
      "height": 729,
      "artBottom": 457
    }
  },
  "def_f0aea36032ce5b12a08f9bd4": {
    "front": {
      "image": "assets/gear-art/epson-213909/erratic-insignator.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/erratic-insignator.png",
      "width": 486,
      "height": 729,
      "artBottom": 539
    }
  },
  "def_d8fb45bdf9402ee81419e01d": {
    "front": {
      "image": "assets/gear-art/epson-213909/exiles-garb.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/exiles-garb.png",
      "width": 492,
      "height": 729,
      "artBottom": 548
    }
  },
  "def_1eff12e231445eee3785d952": {
    "front": {
      "image": "assets/gear-art/epson-213909/shade-shield.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/shade-shield.png",
      "width": 482,
      "height": 729,
      "artBottom": 419
    }
  },
  "def_7e3242b61eac61b1ff162965": {
    "front": {
      "image": "assets/gear-art/epson-213909/shade-armor.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/shade-armor.png",
      "width": 489,
      "height": 729,
      "artBottom": 516
    }
  },
  "def_7b20acc485efbc6451cd3dd9": {
    "front": {
      "image": "assets/gear-art/epson-213909/right-maulfist.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/right-maulfist.png",
      "width": 464,
      "height": 729,
      "artBottom": 471
    }
  },
  "def_4d3cd0d995827be79213e43b": {
    "front": {
      "image": "assets/gear-art/epson-213909/spiral-whip.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/spiral-whip.png",
      "width": 498,
      "height": 745,
      "artBottom": 541
    },
    "back": {
      "image": "assets/gear-art/epson-213909/spiral-buckler.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/spiral-buckler.png",
      "width": 464,
      "height": 749,
      "artBottom": 512
    }
  },
  "def_56f78fce352833b7a83f5d5c": {
    "front": {
      "image": "assets/gear-art/epson-213909/descender.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/descender.png",
      "width": 485,
      "height": 745,
      "artBottom": 550
    },
    "back": {
      "image": "assets/gear-art/epson-213909/devolver.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/devolver.png",
      "width": 486,
      "height": 745,
      "artBottom": 614
    }
  },
  "def_0507b9dec88a470082d25778": {
    "front": {
      "image": "assets/gear-art/epson-213909/probability-blade.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/probability-blade.png",
      "width": 492,
      "height": 745,
      "artBottom": 455
    }
  },
  "def_0d2bbe2219fff1c11f55af6e": {
    "front": {
      "image": "assets/gear-art/epson-213909/shade-mace.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/shade-mace.png",
      "width": 482,
      "height": 745,
      "artBottom": 530
    }
  },
  "def_c857e04acdd64b0fb7737a71": {
    "front": {
      "image": "assets/gear-art/epson-213909/sunlight-gun.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/sunlight-gun.png",
      "width": 489,
      "height": 745,
      "artBottom": 421
    }
  },
  "def_83e19602bbcd09eb4b95b6d5": {
    "front": {
      "image": "assets/gear-art/epson-213909/arc-light-thrower.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/arc-light-thrower.png",
      "width": 464,
      "height": 745,
      "artBottom": 473
    }
  },
  "def_a3c380de040386aae3778c96": {
    "front": {
      "image": "assets/gear-art/epson-213909/icebreakers.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/icebreakers.png",
      "width": 498,
      "height": 749,
      "artBottom": 480
    }
  },
  "def_de56e5c155b5d772b0784004": {
    "front": {
      "image": "assets/gear-art/epson-213909/pithos-linothorax.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/pithos-linothorax.png",
      "width": 485,
      "height": 749,
      "artBottom": 473
    }
  },
  "def_638154b93c9283bfd7be823b": {
    "front": {
      "image": "assets/gear-art/epson-213909/spherical-armor.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/spherical-armor.png",
      "width": 486,
      "height": 749,
      "artBottom": 450
    }
  },
  "def_935725822ec6b2af3d2f450a": {
    "front": {
      "image": "assets/gear-art/epson-213909/visage.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/visage.png",
      "width": 492,
      "height": 749,
      "artBottom": 428
    }
  },
  "def_22eb3c48f9015d4213a5f2b4": {
    "front": {
      "image": "assets/gear-art/epson-213909/spiral-mace.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/spiral-mace.png",
      "width": 482,
      "height": 749,
      "artBottom": 496
    },
    "back": {
      "image": "assets/gear-art/epson-213909/spiral-spear.png",
      "grayscaleImage": "assets/gear-art/epson-213909/grayscale/spiral-spear.png",
      "width": 489,
      "height": 749,
      "artBottom": 543
    }
  },
  "def_4f268f7293c5f6b6e9844a8b": {
    "front": {
      "image": "assets/gear-art/epson-214451/feather-shield.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/feather-shield.png",
      "width": 488,
      "height": 728,
      "artBottom": 432
    }
  },
  "def_f02e4d558a1f1aac55f01f3d": {
    "front": {
      "image": "assets/gear-art/epson-214451/looper-guard.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/looper-guard.png",
      "width": 484,
      "height": 728,
      "artBottom": 457
    }
  },
  "def_64c823b6638ceec5f6177db9": {
    "front": {
      "image": "assets/gear-art/epson-214451/fatesafer.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/fatesafer.png",
      "width": 490,
      "height": 728,
      "artBottom": 522
    }
  },
  "def_dac9f33d463d79ea2f8e2041": {
    "front": {
      "image": "assets/gear-art/epson-214451/ontological-module.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/ontological-module.png",
      "width": 486,
      "height": 728,
      "artBottom": 436
    }
  },
  "def_31a4cc2d6f0c6765fc4118c1": {
    "front": {
      "image": "assets/gear-art/epson-214451/black-ice-kothornos.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/black-ice-kothornos.png",
      "width": 484,
      "height": 728,
      "artBottom": 344
    }
  },
  "def_a140ff12e43756acf0c58d68": {
    "front": {
      "image": "assets/gear-art/epson-214451/iceblock-armor.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/iceblock-armor.png",
      "width": 483,
      "height": 728,
      "artBottom": 499
    }
  },
  "def_dc08986eb76a27a20925d7ef": {
    "front": {
      "image": "assets/gear-art/epson-214451/polished-ice-shield.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/polished-ice-shield.png",
      "width": 475,
      "height": 728,
      "artBottom": 472
    }
  },
  "def_b7df32375b0d054a8af88f78": {
    "front": {
      "image": "assets/gear-art/epson-214451/scaling-gear-prototype.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/scaling-gear-prototype.png",
      "width": 488,
      "height": 743,
      "artBottom": 461
    }
  },
  "def_15987b3264c7ec06b165f828": {
    "front": {
      "image": "assets/gear-art/epson-214451/ignition-spear.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/ignition-spear.png",
      "width": 484,
      "height": 743,
      "artBottom": 517
    }
  },
  "def_d66c30fb5cabcf2a13f1e898": {
    "back": {
      "image": "assets/gear-art/epson-214451/hidden-xiphos.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/hidden-xiphos.png",
      "width": 490,
      "height": 743,
      "artBottom": 461
    },
    "front": {
      "image": "assets/gear-art/epson-214451/hammer-sword.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/hammer-sword.png",
      "width": 486,
      "height": 743,
      "artBottom": 538
    }
  },
  "def_332976754f4b76ddc75396b8": {
    "back": {
      "image": "assets/gear-art/epson-214451/barbed-blade.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/barbed-blade.png",
      "width": 484,
      "height": 743,
      "artBottom": 506
    },
    "front": {
      "image": "assets/gear-art/epson-214451/barbed-saw.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/barbed-saw.png",
      "width": 483,
      "height": 743,
      "artBottom": 508
    }
  },
  "def_88ccb387e0672eccdf4a7aa3": {
    "front": {
      "image": "assets/gear-art/epson-214451/oracowl.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/oracowl.png",
      "width": 475,
      "height": 743,
      "artBottom": 411
    }
  },
  "def_78f23828883f8bef2338dcc0": {
    "front": {
      "image": "assets/gear-art/epson-214451/agathos-agitator.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/agathos-agitator.png",
      "width": 488,
      "height": 769,
      "artBottom": 461
    }
  },
  "def_52f7a1d7f814dae33f555168": {
    "front": {
      "image": "assets/gear-art/epson-214451/aristeia-inducer.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/aristeia-inducer.png",
      "width": 484,
      "height": 769,
      "artBottom": 421
    }
  },
  "def_1f7d02b48fa733a9c120286b": {
    "front": {
      "image": "assets/gear-art/epson-214451/homeric-engine.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/homeric-engine.png",
      "width": 490,
      "height": 769,
      "artBottom": 477
    }
  },
  "def_27d3b23ad760f9044348c2fe": {
    "front": {
      "image": "assets/gear-art/epson-214451/exobone-armor.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/exobone-armor.png",
      "width": 486,
      "height": 769,
      "artBottom": 518
    }
  },
  "def_514949213076ea4f7c573375": {
    "front": {
      "image": "assets/gear-art/epson-214451/feather-linothorax.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/feather-linothorax.png",
      "width": 484,
      "height": 769,
      "artBottom": 547
    }
  },
  "def_80e8d27819a5d68e4e736abb": {
    "front": {
      "image": "assets/gear-art/epson-214451/enigma-of-transformation.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/enigma-of-transformation.png",
      "width": 483,
      "height": 769,
      "artBottom": 407
    }
  },
  "def_6d9c33195eae660f7abe9536": {
    "front": {
      "image": "assets/gear-art/epson-214451/horseskull-pauldron.png",
      "grayscaleImage": "assets/gear-art/epson-214451/grayscale/horseskull-pauldron.png",
      "width": 475,
      "height": 769,
      "artBottom": 443
    }
  },
  "def_0903c389f83fe3c4100ed06a": {
    "front": {
      "image": "assets/gear-art/epson-215042/beholder-fists.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/beholder-fists.png",
      "width": 489,
      "height": 731,
      "artBottom": 435
    }
  },
  "def_5ee04e0a2134a065aba93d0f": {
    "front": {
      "image": "assets/gear-art/epson-215042/paradont.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/paradont.png",
      "width": 487,
      "height": 731,
      "artBottom": 514
    }
  },
  "def_60aff897c46c3d865731ba13": {
    "front": {
      "image": "assets/gear-art/epson-215042/echo-eaters.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/echo-eaters.png",
      "width": 491,
      "height": 731,
      "artBottom": 430
    }
  },
  "def_87adbb9094b35a544fd46368": {
    "front": {
      "image": "assets/gear-art/epson-215042/kakos-implant.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/kakos-implant.png",
      "width": 485,
      "height": 731,
      "artBottom": 484
    }
  },
  "def_feefe2b44d5db716d996ad80": {
    "front": {
      "image": "assets/gear-art/epson-215042/argocryptex-beta.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/argocryptex-beta.png",
      "width": 482,
      "height": 731,
      "artBottom": 457
    }
  },
  "def_3f13448a0a2860ab13007fc7": {
    "front": {
      "image": "assets/gear-art/epson-215042/argocryptex-alpha.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/argocryptex-alpha.png",
      "width": 487,
      "height": 731,
      "artBottom": 417
    }
  },
  "def_933a6812cfbd8cc6fef10cb1": {
    "front": {
      "image": "assets/gear-art/epson-215042/argocryptex-gamma.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/argocryptex-gamma.png",
      "width": 475,
      "height": 731,
      "artBottom": 496
    }
  },
  "def_7cbe160edf7d870de4b74f16": {
    "front": {
      "image": "assets/gear-art/epson-215042/voice-of-the-people.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/voice-of-the-people.png",
      "width": 489,
      "height": 752,
      "artBottom": 541
    },
    "back": {
      "image": "assets/gear-art/epson-215411/peaceful-transition.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/peaceful-transition.png",
      "width": 471,
      "height": 724,
      "artBottom": 387
    }
  },
  "def_afc36c422445c38c24b3547c": {
    "front": {
      "image": "assets/gear-art/epson-215042/skyfall.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/skyfall.png",
      "width": 487,
      "height": 752,
      "artBottom": 469
    }
  },
  "def_addbb52520d9c36f5b3df9b1": {
    "front": {
      "image": "assets/gear-art/epson-215042/sunreach.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/sunreach.png",
      "width": 491,
      "height": 752,
      "artBottom": 451
    }
  },
  "def_f7e4a0ddd3d4611d27f4dc36": {
    "front": {
      "image": "assets/gear-art/epson-215042/daedalus-s-flight.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/daedalus-s-flight.png",
      "width": 485,
      "height": 752,
      "artBottom": 612
    }
  },
  "def_3c848a2992b92fc45d4a700d": {
    "front": {
      "image": "assets/gear-art/epson-215042/black-ice-sword.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/black-ice-sword.png",
      "width": 482,
      "height": 752,
      "artBottom": 489
    }
  },
  "def_6fcc66c4e447083bcecf6367": {
    "front": {
      "image": "assets/gear-art/epson-215042/extinction-cestus.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/extinction-cestus.png",
      "width": 487,
      "height": 752,
      "artBottom": 566
    }
  },
  "def_fd708ac12f2f8229709f5df4": {
    "front": {
      "image": "assets/gear-art/epson-215042/time-s-arrow.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/time-s-arrow.png",
      "width": 475,
      "height": 752,
      "artBottom": 455
    }
  },
  "def_3100c6d44764814c51121f6a": {
    "front": {
      "image": "assets/gear-art/epson-215042/exoaegis.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/exoaegis.png",
      "width": 489,
      "height": 756,
      "artBottom": 507
    },
    "back": {
      "image": "assets/gear-art/epson-215042/razorbow.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/razorbow.png",
      "width": 487,
      "height": 756,
      "artBottom": 478
    }
  },
  "def_4c2fe5f96b7d68e3dfc616d7": {
    "front": {
      "image": "assets/gear-art/epson-215042/sun-spear.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/sun-spear.png",
      "width": 491,
      "height": 756,
      "artBottom": 575
    },
    "back": {
      "image": "assets/gear-art/epson-215042/sun-axe.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/sun-axe.png",
      "width": 485,
      "height": 756,
      "artBottom": 568
    }
  },
  "def_b91831aeeb3824119b5a2f6e": {
    "back": {
      "image": "assets/gear-art/epson-215042/sun-cutter.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/sun-cutter.png",
      "width": 482,
      "height": 756,
      "artBottom": 435
    },
    "front": {
      "image": "assets/gear-art/epson-215042/sun-disc.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/sun-disc.png",
      "width": 487,
      "height": 756,
      "artBottom": 453
    }
  },
  "def_f36ef41cb0988b77754364a4": {
    "front": {
      "image": "assets/gear-art/epson-215042/red-polis.png",
      "grayscaleImage": "assets/gear-art/epson-215042/grayscale/red-polis.png",
      "width": 475,
      "height": 756,
      "artBottom": 317
    }
  },
  "def_ade9a7db1df2d1a0b10643e1": {
    "front": {
      "image": "assets/gear-art/epson-215411/regression-agent.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/regression-agent.png",
      "width": 498,
      "height": 724,
      "artBottom": 543
    }
  },
  "def_855cc5a141894bc31c0b9a8b": {
    "front": {
      "image": "assets/gear-art/epson-215411/icelixir.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/icelixir.png",
      "width": 491,
      "height": 724,
      "artBottom": 480
    }
  },
  "def_fc1b58ddaa0b7cdc782d5d79": {
    "front": {
      "image": "assets/gear-art/epson-215411/spike-breakers.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/spike-breakers.png",
      "width": 483,
      "height": 724,
      "artBottom": 403
    }
  },
  "def_3206ed0a84962172af05acd5": {
    "front": {
      "image": "assets/gear-art/epson-215411/prototype-trespass-device.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/prototype-trespass-device.png",
      "width": 484,
      "height": 724,
      "artBottom": 489
    }
  },
  "def_8723666db5ec62c34a0a45c3": {
    "front": {
      "image": "assets/gear-art/epson-215411/time-booster.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/time-booster.png",
      "width": 485,
      "height": 724,
      "artBottom": 469
    }
  },
  "def_e6eff6534d52cad8c0b107a6": {
    "front": {
      "image": "assets/gear-art/epson-215411/sun-guard.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/sun-guard.png",
      "width": 484,
      "height": 724,
      "artBottom": 457
    }
  },
  "def_2b40b95f33472d2c3b6130c6": {
    "front": {
      "image": "assets/gear-art/epson-215411/spiral-shield.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/spiral-shield.png",
      "width": 498,
      "height": 748,
      "artBottom": 471
    }
  },
  "def_48e5f295e335375eed03ba1c": {
    "front": {
      "image": "assets/gear-art/epson-215411/siren-cataphract.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/siren-cataphract.png",
      "width": 491,
      "height": 748,
      "artBottom": 483
    }
  },
  "def_b9405136f1c7c983c6375720": {
    "front": {
      "image": "assets/gear-art/epson-215411/siren-coral-panoply.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/siren-coral-panoply.png",
      "width": 483,
      "height": 748,
      "artBottom": 526
    }
  },
  "def_d773534f129d232e8b5e60c9": {
    "front": {
      "image": "assets/gear-art/epson-215411/sirentusks.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/sirentusks.png",
      "width": 484,
      "height": 748,
      "artBottom": 555
    }
  },
  "def_eb9f835643337e388a186303": {
    "front": {
      "image": "assets/gear-art/epson-215411/spiradiscus.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/spiradiscus.png",
      "width": 485,
      "height": 748,
      "artBottom": 528
    }
  },
  "def_fd59bce1febd1a96706116f0": {
    "front": {
      "image": "assets/gear-art/epson-215411/spiral-spada.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/spiral-spada.png",
      "width": 484,
      "height": 748,
      "artBottom": 576
    }
  },
  "def_a81b90444ed48020e904a5ce": {
    "front": {
      "image": "assets/gear-art/epson-215411/true-sirenblade.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/true-sirenblade.png",
      "width": 471,
      "height": 748,
      "artBottom": 514
    }
  },
  "def_ed248ffa0176c6bf2eca0fdb": {
    "front": {
      "image": "assets/gear-art/epson-215411/paradox-guard.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/paradox-guard.png",
      "width": 498,
      "height": 756,
      "artBottom": 364
    }
  },
  "def_eec969b9ba4d2275660d0968": {
    "front": {
      "image": "assets/gear-art/epson-215411/hourglass-necklace.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/hourglass-necklace.png",
      "width": 491,
      "height": 756,
      "artBottom": 486
    }
  },
  "def_67d7096c6e93243f00be05a5": {
    "front": {
      "image": "assets/gear-art/epson-215411/parallel-anchor.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/parallel-anchor.png",
      "width": 483,
      "height": 756,
      "artBottom": 500
    }
  },
  "def_db9e38fae3a1db798e95011e": {
    "front": {
      "image": "assets/gear-art/epson-215411/glacial-fabric.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/glacial-fabric.png",
      "width": 484,
      "height": 756,
      "artBottom": 547
    }
  },
  "def_b6cfef07345c8354898539e1": {
    "front": {
      "image": "assets/gear-art/epson-215411/timeline-synchronizer.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/timeline-synchronizer.png",
      "width": 485,
      "height": 756,
      "artBottom": 511
    }
  },
  "def_b96bca4a05047b99eb999aee": {
    "front": {
      "image": "assets/gear-art/epson-215411/recall-shell.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/recall-shell.png",
      "width": 484,
      "height": 756,
      "artBottom": 441
    }
  },
  "def_750f26d255f1f0da09f4de20": {
    "front": {
      "image": "assets/gear-art/epson-215411/siren-mask.png",
      "grayscaleImage": "assets/gear-art/epson-215411/grayscale/siren-mask.png",
      "width": 471,
      "height": 756,
      "artBottom": 412
    }
  },
  "def_473eaefddada5f90a9ed51c0": {
    "front": {
      "image": "assets/gear-art/epson-215757/paradox-scanner.png",
      "grayscaleImage": "assets/gear-art/epson-215757/grayscale/paradox-scanner.png",
      "width": 484,
      "height": 728,
      "artBottom": 511
    }
  },
  "def_fe83e3d4fe5a53792196f7c3": {
    "front": {
      "image": "assets/gear-art/epson-215757/fatesafe.png",
      "grayscaleImage": "assets/gear-art/epson-215757/grayscale/fatesafe.png",
      "width": 479,
      "height": 728,
      "artBottom": 524
    }
  }
};
