// Generated by scripts/extract-gear-art.py; keyed by persistent definition and face IDs.
import type { GearArtwork } from '../domain/cards.ts';

export const gearArtwork: Readonly<Record<string, Partial<Record<'front' | 'back', GearArtwork>>>> = {
  "def_61558188902e56ca96781073": {
    "front": {
      "image": "assets/gear-art/cycle2-a/mazed-cestus.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/mazed-cestus.png",
      "width": 488,
      "height": 728,
      "artBottom": 468
    }
  },
  "def_ac6cc275dc91216e75e05000": {
    "front": {
      "image": "assets/gear-art/cycle2-a/temenos-scale-shield.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/temenos-scale-shield.png",
      "width": 486,
      "height": 728,
      "artBottom": 448
    },
    "back": {
      "image": "assets/gear-art/cycle2-a/temenos-scale-umbrella.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/temenos-scale-umbrella.png",
      "width": 504,
      "height": 745,
      "artBottom": 429
    }
  },
  "def_c5f40c37c8abd0f63325448f": {
    "front": {
      "image": "assets/gear-art/cycle2-a/temenos-xiphos.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/temenos-xiphos.png",
      "width": 488,
      "height": 728,
      "artBottom": 521
    },
    "back": {
      "image": "assets/gear-art/cycle2-a/temenos-whip.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/temenos-whip.png",
      "width": 487,
      "height": 728,
      "artBottom": 438
    }
  },
  "def_5b660ac8bbf14eeaf479685a": {
    "front": {
      "image": "assets/gear-art/cycle2-a/puzzle-axe.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/puzzle-axe.png",
      "width": 490,
      "height": 728,
      "artBottom": 524
    }
  },
  "def_8a4a927fa3501e20e64debae": {
    "front": {
      "image": "assets/gear-art/cycle2-a/labyrinth-mauler.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/labyrinth-mauler.png",
      "width": 487,
      "height": 728,
      "artBottom": 460
    }
  },
  "def_63677eb8093f4b86a3e7a586": {
    "front": {
      "image": "assets/gear-art/cycle2-a/labyrinth-armor.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/labyrinth-armor.png",
      "width": 470,
      "height": 728,
      "artBottom": 409
    }
  },
  "def_560add20be9cf8399e99dc79": {
    "front": {
      "image": "assets/gear-art/cycle2-a/scale-chakram.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/scale-chakram.png",
      "width": 485,
      "height": 745,
      "artBottom": 446
    }
  },
  "def_e341257ffb5fe8bfb2e80ed5": {
    "front": {
      "image": "assets/gear-art/cycle2-a/mazechute.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/mazechute.png",
      "width": 482,
      "height": 745,
      "artBottom": 434
    }
  },
  "def_d37dbc8fdc104b4cbaa96fc0": {
    "back": {
      "image": "assets/gear-art/cycle2-a/pseudomidion.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/pseudomidion.png",
      "width": 483,
      "height": 745,
      "artBottom": 554
    },
    "front": {
      "image": "assets/gear-art/cycle2-a/longinus.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/longinus.png",
      "width": 486,
      "height": 745,
      "artBottom": 469
    }
  },
  "def_148586339664a76b23490970": {
    "front": {
      "image": "assets/gear-art/cycle2-a/mazegma.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/mazegma.png",
      "width": 485,
      "height": 745,
      "artBottom": 445
    }
  },
  "def_b12bd681320ce723c4e8e6c6": {
    "front": {
      "image": "assets/gear-art/cycle2-a/stonewall.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/stonewall.png",
      "width": 471,
      "height": 745,
      "artBottom": 446
    }
  },
  "def_f27a1484fa260d51ca3ef40a": {
    "front": {
      "image": "assets/gear-art/cycle2-a/ambrostilts.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/ambrostilts.png",
      "width": 500,
      "height": 759,
      "artBottom": 514
    }
  },
  "def_6f01f1e8ad627539efbaa47c": {
    "front": {
      "image": "assets/gear-art/cycle2-a/amphoras-belt.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/amphoras-belt.png",
      "width": 485,
      "height": 759,
      "artBottom": 460
    }
  },
  "def_11163aef562fe4505b980329": {
    "front": {
      "image": "assets/gear-art/cycle2-a/isokratos-limiter.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/isokratos-limiter.png",
      "width": 481,
      "height": 759,
      "artBottom": 427
    }
  },
  "def_072b6e2a95e6c76278877983": {
    "front": {
      "image": "assets/gear-art/cycle2-a/stepping-stone.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/stepping-stone.png",
      "width": 487,
      "height": 759,
      "artBottom": 375
    }
  },
  "def_459ec46e5862daf2ef2ae00f": {
    "front": {
      "image": "assets/gear-art/cycle2-a/repurposed-cryptex.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/repurposed-cryptex.png",
      "width": 487,
      "height": 759,
      "artBottom": 427
    }
  },
  "def_d57bf501fdfa02a89d66518c": {
    "front": {
      "image": "assets/gear-art/cycle2-a/conqueror-nail.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/conqueror-nail.png",
      "width": 486,
      "height": 759,
      "artBottom": 354
    }
  },
  "def_ab4951636e0ce3c72b9279cb": {
    "front": {
      "image": "assets/gear-art/cycle2-a/pursuer-ultimatum.png",
      "grayscaleImage": "assets/gear-art/cycle2-a/grayscale/pursuer-ultimatum.png",
      "width": 470,
      "height": 759,
      "artBottom": 591
    }
  },
  "def_3b6bf24413178ff91c4a0f21": {
    "front": {
      "image": "assets/gear-art/epson-210624/great-breaker.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/great-breaker.png",
      "width": 484,
      "height": 727,
      "artBottom": 484
    }
  },
  "def_c9381d7b0670cd2782532f6f": {
    "front": {
      "image": "assets/gear-art/epson-210624/impact-armor.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/impact-armor.png",
      "width": 486,
      "height": 727,
      "artBottom": 458
    }
  },
  "def_39fb71e037825c0881e5fe3a": {
    "front": {
      "image": "assets/gear-art/epson-210624/collision-shield.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/collision-shield.png",
      "width": 488,
      "height": 727,
      "artBottom": 494
    }
  },
  "def_565980ba3dd68ac1a19f6ba0": {
    "front": {
      "image": "assets/gear-art/epson-210624/iapetus-lifesaver.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/iapetus-lifesaver.png",
      "width": 484,
      "height": 727,
      "artBottom": 526
    }
  },
  "def_4f67dc040937547c288750f4": {
    "front": {
      "image": "assets/gear-art/epson-210624/achillean-hectors.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/achillean-hectors.png",
      "width": 484,
      "height": 727,
      "artBottom": 441
    }
  },
  "def_3c014172da91bf78d6cfb2e8": {
    "front": {
      "image": "assets/gear-art/epson-210624/boost-kothornos.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/boost-kothornos.png",
      "width": 484,
      "height": 727,
      "artBottom": 494
    }
  },
  "def_e3d3918978496f6da2662f4f": {
    "front": {
      "image": "assets/gear-art/epson-210624/control-module.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/control-module.png",
      "width": 473,
      "height": 727,
      "artBottom": 467
    }
  },
  "def_23b991706c979449431a4f08": {
    "front": {
      "image": "assets/gear-art/epson-210624/lethe-guard.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/lethe-guard.png",
      "width": 484,
      "height": 746,
      "artBottom": 376
    }
  },
  "def_dee1a57fa844368bba3473fd": {
    "front": {
      "image": "assets/gear-art/epson-210624/asklepios-node.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/asklepios-node.png",
      "width": 486,
      "height": 746,
      "artBottom": 519
    }
  },
  "def_cdddf6feacb4a21fdc5724fc": {
    "front": {
      "image": "assets/gear-art/epson-210624/covenant.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/covenant.png",
      "width": 489,
      "height": 746,
      "artBottom": 420
    }
  },
  "def_d3f2c8ebc688e9de114aada2": {
    "front": {
      "image": "assets/gear-art/epson-210624/siegetower-pauldron.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/siegetower-pauldron.png",
      "width": 488,
      "height": 746,
      "artBottom": 420
    }
  },
  "def_74865d39073e1119ee52d29d": {
    "front": {
      "image": "assets/gear-art/epson-210624/watchtower-pauldron.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/watchtower-pauldron.png",
      "width": 486,
      "height": 746,
      "artBottom": 418
    }
  },
  "def_66c74d62c9da72087b81c6e2": {
    "front": {
      "image": "assets/gear-art/epson-210624/relief-cestus.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/relief-cestus.png",
      "width": 484,
      "height": 746,
      "artBottom": 496
    }
  },
  "def_e77b306d0dbfd7c7e8f398ac": {
    "front": {
      "image": "assets/gear-art/epson-210624/stone-relief-armor.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/stone-relief-armor.png",
      "width": 473,
      "height": 746,
      "artBottom": 511
    }
  },
  "def_024cb29f78198ec49342b34a": {
    "front": {
      "image": "assets/gear-art/epson-210624/grand-ramaxe.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/grand-ramaxe.png",
      "width": 484,
      "height": 745,
      "artBottom": 543
    }
  },
  "def_4d0d52e413f7d54ff269212b": {
    "front": {
      "image": "assets/gear-art/epson-210624/chain-whip.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/chain-whip.png",
      "width": 484,
      "height": 745,
      "artBottom": 547
    }
  },
  "def_4cfe7fa97cd49fbf87bb7735": {
    "front": {
      "image": "assets/gear-art/epson-210624/fireboat.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/fireboat.png",
      "width": 486,
      "height": 745,
      "artBottom": 566
    }
  },
  "def_dbb2d468ccb5bb63ebfb5ea7": {
    "front": {
      "image": "assets/gear-art/epson-210624/eviscerators.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/eviscerators.png",
      "width": 490,
      "height": 745,
      "artBottom": 518
    }
  },
  "def_044e1bc110fff9b60e0230f9": {
    "front": {
      "image": "assets/gear-art/epson-210624/vaulting-rope.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/vaulting-rope.png",
      "width": 486,
      "height": 745,
      "artBottom": 540
    }
  },
  "def_db711e05caf4d00fef758b0d": {
    "back": {
      "image": "assets/gear-art/epson-210624/metabow.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/metabow.png",
      "width": 486,
      "height": 745,
      "artBottom": 530
    },
    "front": {
      "image": "assets/gear-art/epson-210624/metasword.png",
      "grayscaleImage": "assets/gear-art/epson-210624/grayscale/metasword.png",
      "width": 480,
      "height": 745,
      "artBottom": 604
    }
  },
  "def_54b6ba6736297a521535b8a9": {
    "front": {
      "image": "assets/gear-art/epson-211018/katarus.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/katarus.png",
      "width": 500,
      "height": 731,
      "artBottom": 516
    }
  },
  "def_d50974c7ea7812cfa76eb1d5": {
    "front": {
      "image": "assets/gear-art/epson-211018/muck-armor.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/muck-armor.png",
      "width": 489,
      "height": 731,
      "artBottom": 407
    }
  },
  "def_de2547f0a2fbda3870f6a647": {
    "back": {
      "image": "assets/gear-art/epson-211018/ladder-mode.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/ladder-mode.png",
      "width": 488,
      "height": 731,
      "artBottom": 403
    },
    "front": {
      "image": "assets/gear-art/epson-211018/ladder-buckler.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/ladder-buckler.png",
      "width": 476,
      "height": 731,
      "artBottom": 424
    }
  },
  "def_6e30e99b6d4b1a2eaf107e99": {
    "front": {
      "image": "assets/gear-art/epson-211018/muckbane.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/muckbane.png",
      "width": 485,
      "height": 731,
      "artBottom": 624
    }
  },
  "def_a64a5f0b6e29f97b7bcf520e": {
    "front": {
      "image": "assets/gear-art/epson-211018/cyclostus.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/cyclostus.png",
      "width": 472,
      "height": 731,
      "artBottom": 406
    }
  },
  "def_b8081b0e2ccba3a7797a579d": {
    "back": {
      "image": "assets/gear-art/epson-211018/boom-pole.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/boom-pole.png",
      "width": 499,
      "height": 743,
      "artBottom": 343
    },
    "front": {
      "image": "assets/gear-art/epson-211018/boom-spear.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/boom-spear.png",
      "width": 472,
      "height": 764,
      "artBottom": 535
    }
  },
  "def_6e9c85fc4e34e78d79c312c7": {
    "front": {
      "image": "assets/gear-art/epson-211018/muck-bludgeon.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/muck-bludgeon.png",
      "width": 490,
      "height": 743,
      "artBottom": 521
    }
  },
  "def_0e5cc0c028a1e6b02777c401": {
    "front": {
      "image": "assets/gear-art/epson-211018/dragon-bellow.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/dragon-bellow.png",
      "width": 486,
      "height": 743,
      "artBottom": 470
    }
  },
  "def_c664e37d1bccbf12f92532d1": {
    "front": {
      "image": "assets/gear-art/epson-211018/ambrosia-trocar.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/ambrosia-trocar.png",
      "width": 488,
      "height": 743,
      "artBottom": 545
    }
  },
  "def_785f5a7f4b5fac9edf01666c": {
    "front": {
      "image": "assets/gear-art/epson-211018/maulmace.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/maulmace.png",
      "width": 476,
      "height": 743,
      "artBottom": 517
    }
  },
  "def_6eb329f1f26c218f89699f3e": {
    "front": {
      "image": "assets/gear-art/epson-211018/needle-sword.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/needle-sword.png",
      "width": 485,
      "height": 743,
      "artBottom": 472
    }
  },
  "def_7d504be35f4966b43139cfa8": {
    "front": {
      "image": "assets/gear-art/epson-211018/vaulting-spear.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/vaulting-spear.png",
      "width": 472,
      "height": 743,
      "artBottom": 426
    }
  },
  "def_1d21790aa90c51fb97044897": {
    "front": {
      "image": "assets/gear-art/epson-211018/temple-camo.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/temple-camo.png",
      "width": 495,
      "height": 764,
      "artBottom": 420
    }
  },
  "def_3e04a88ca2ef6bc9505532d6": {
    "front": {
      "image": "assets/gear-art/epson-211018/faceshield.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/faceshield.png",
      "width": 492,
      "height": 764,
      "artBottom": 458
    }
  },
  "def_fc859c21e41ddbb4af93f5ad": {
    "front": {
      "image": "assets/gear-art/epson-211018/roll-breakers.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/roll-breakers.png",
      "width": 488,
      "height": 764,
      "artBottom": 512
    }
  },
  "def_f32459dfab4321815c42457e": {
    "front": {
      "image": "assets/gear-art/epson-211018/squat-armor.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/squat-armor.png",
      "width": 488,
      "height": 764,
      "artBottom": 442
    }
  },
  "def_d4e33a69642dc1688e9ec15e": {
    "front": {
      "image": "assets/gear-art/epson-211018/pithos-armor.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/pithos-armor.png",
      "width": 476,
      "height": 764,
      "artBottom": 456
    }
  },
  "def_5a32b9d80bddc54f78fc0e24": {
    "front": {
      "image": "assets/gear-art/epson-211018/chimeric-xiphos.png",
      "grayscaleImage": "assets/gear-art/epson-211018/grayscale/chimeric-xiphos.png",
      "width": 485,
      "height": 764,
      "artBottom": 427
    }
  },
  "def_0eea196607c08352330a66d3": {
    "front": {
      "image": "assets/gear-art/epson-211609/carver-kopis.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/carver-kopis.png",
      "width": 491,
      "height": 734,
      "artBottom": 565
    }
  },
  "def_f01d60a752785a861b737dbc": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-totem.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-totem.png",
      "width": 484,
      "height": 734,
      "artBottom": 347
    }
  },
  "def_54acada1dd3d96d300f05c15": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-knives.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-knives.png",
      "width": 486,
      "height": 734,
      "artBottom": 468
    }
  },
  "def_8356a32e9d8389ef18c1600c": {
    "front": {
      "image": "assets/gear-art/epson-211609/spartan-kopis.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/spartan-kopis.png",
      "width": 487,
      "height": 734,
      "artBottom": 504
    }
  },
  "def_7953a7a5a42900ca3b7ebce9": {
    "front": {
      "image": "assets/gear-art/epson-211609/spartan-war-axe.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/spartan-war-axe.png",
      "width": 486,
      "height": 734,
      "artBottom": 557
    }
  },
  "def_a2b46c0958ba8e8204b629ca": {
    "front": {
      "image": "assets/gear-art/epson-211609/labyrinthization.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/labyrinthization.png",
      "width": 486,
      "height": 734,
      "artBottom": 408
    }
  },
  "def_8a8cad406c251d20a1eefad5": {
    "front": {
      "image": "assets/gear-art/epson-211609/medusa-extract.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/medusa-extract.png",
      "width": 464,
      "height": 734,
      "artBottom": 446
    }
  },
  "def_3f1413dba827ee88eefbe8c4": {
    "front": {
      "image": "assets/gear-art/epson-211609/heavy-spear.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/heavy-spear.png",
      "width": 484,
      "height": 760,
      "artBottom": 555
    }
  },
  "def_daf5328eb7b0499a62e07465": {
    "front": {
      "image": "assets/gear-art/epson-211609/gastraphetes.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/gastraphetes.png",
      "width": 486,
      "height": 760,
      "artBottom": 497
    }
  },
  "def_20ecd9e4ed4cf37856d0a0fc": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-khopesh.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-khopesh.png",
      "width": 487,
      "height": 760,
      "artBottom": 646
    }
  },
  "def_1e96a92c7288054dc7cdb7d0": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-forge-hammer.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-forge-hammer.png",
      "width": 486,
      "height": 760,
      "artBottom": 505
    }
  },
  "def_802be492d4e7d41a955bed97": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-visor.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-visor.png",
      "width": 486,
      "height": 760,
      "artBottom": 425
    }
  },
  "def_4a60bba7e035ddb3aa5a3097": {
    "front": {
      "image": "assets/gear-art/epson-211609/cyclopean-linothorax.png",
      "grayscaleImage": "assets/gear-art/epson-211609/grayscale/cyclopean-linothorax.png",
      "width": 464,
      "height": 760,
      "artBottom": 529
    }
  }
};
